//
//  IncomeAndExpenseWorker.swift
//  Money Pack Pro
//
//  Created by itthipon wiwatthanasathit on 10/13/2560 BE.
//  Copyright (c) 2560 Dev7. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class IncomeAndExpenseWorker
{
  func createArrayImage(Completion:@escaping([ItemType]) ->(Void))
  {
    var itemTypes:[ItemType] = []
    let food = ItemType(nameImage: "ic_0_white", descImage: "Food", colorImage: COLOR_FOOD)
    let clothing = ItemType(nameImage: "ic_1_white", descImage: "Clothing", colorImage: COLOR_CLOTHING)
    let salary = ItemType(nameImage: "ic_2_white", descImage: "Salary", colorImage: COLOR_SALARY)
    let market = ItemType(nameImage: "ic_3_white", descImage: "Market", colorImage: COLOR_MARKET)
    let medical = ItemType(nameImage: "ic_4_white", descImage: "Medical", colorImage: COLOR_MEDICAL)
    let savings = ItemType(nameImage: "ic_5_white", descImage: "Savings", colorImage: COLOR_SAVING)
    let transportation = ItemType(nameImage: "ic_6_white", descImage: "Transportation", colorImage: COLOR_TRANSPORTATION)
    let beer = ItemType(nameImage: "ic_7_white", descImage: "Beer", colorImage: COLOR_PARTY)
    let phone = ItemType(nameImage: "ic_8_white", descImage: "Phone", colorImage: COLOR_PHONE)
    let beauty = ItemType(nameImage: "ic_9_white", descImage: "Beauty", colorImage: COLOR_BEAUTY)
    let electronic = ItemType(nameImage: "ic_10_white", descImage: "Electronic", colorImage: COLOR_ELECTRONIC)
    let education = ItemType(nameImage: "ic_11_white", descImage: "Education", colorImage: COLOR_EDUCATION)
    let card = ItemType(nameImage: "ic_12_white", descImage: "Card", colorImage: COLOR_CARD)
    let apartment = ItemType(nameImage: "ic_13_white", descImage: "Apartment", colorImage: COLOR_APARTMENT)
    let drink = ItemType(nameImage: "ic_14_white", descImage: "Drink", colorImage: COLOR_DRINK)
    let car = ItemType(nameImage: "ic_15_white", descImage: "Car", colorImage: COLOR_MARKET)
    let fruit = ItemType(nameImage: "ic_16_white", descImage: "Fruit", colorImage: COLOR_FRUIT)
    let accessories = ItemType(nameImage: "ic_17_white", descImage: "Accessories", colorImage: COLOR_ACCESSORY)
    let sweets = ItemType(nameImage: "ic_18_white", descImage: "Sweets", colorImage: COLOR_SWEETS)
    let music = ItemType(nameImage: "ic_19_white", descImage: "Music", colorImage: COLOR_MUSIC)
    
    itemTypes.append(food)
    itemTypes.append(market)
    itemTypes.append(clothing)
    itemTypes.append(transportation)
    itemTypes.append(apartment)
    
    itemTypes.append(salary)
    itemTypes.append(savings)
    itemTypes.append(medical)
    itemTypes.append(beer)
    itemTypes.append(phone)
    
    itemTypes.append(beauty)
    itemTypes.append(electronic)
    itemTypes.append(education)
    itemTypes.append(card)
    itemTypes.append(drink)
    
    itemTypes.append(car)
    itemTypes.append(fruit)
    itemTypes.append(accessories)
    itemTypes.append(sweets)
    itemTypes.append(music)
    
    Completion(itemTypes)
  }
}
