//
//  IncomeAndExpenseInteractor.swift
//  Money Pack Pro
//
//  Created by itthipon wiwatthanasathit on 10/13/2560 BE.
//  Copyright (c) 2560 Dev7. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IncomeAndExpenseBusinessLogic
{
  func fetchItemType(request: IncomeAndExpense.FetchItemType.Request)
}

protocol IncomeAndExpenseDataStore
{ 
  var itemTypes: [ItemType]? { get }
}

class IncomeAndExpenseInteractor: IncomeAndExpenseBusinessLogic, IncomeAndExpenseDataStore
{
  var presenter: IncomeAndExpensePresentationLogic?
  var worker: IncomeAndExpenseWorker?
  
  var itemTypes: [ItemType]?
  
  // MARK: Do something
  
  func fetchItemType(request: IncomeAndExpense.FetchItemType.Request)
  {
    worker = IncomeAndExpenseWorker()
    worker?.createArrayImage(Completion: { (itemTypes) -> (Void) in
      self.itemTypes = itemTypes
      let response = IncomeAndExpense.FetchItemType.Response(ItemTypes: itemTypes)
      self.presenter?.presentFetchedItemType(response: response)
    })
    
    
  }
}
