//
//  IncomeAndExpenseRouter.swift
//  Money Pack Pro
//
//  Created by itthipon wiwatthanasathit on 10/13/2560 BE.
//  Copyright (c) 2560 Dev7. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IncomeAndExpenseRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol IncomeAndExpenseDataPassing
{
  var dataStore: IncomeAndExpenseDataStore? { get }
}

class IncomeAndExpenseRouter: NSObject, IncomeAndExpenseRoutingLogic, IncomeAndExpenseDataPassing
{
  weak var viewController: IncomeAndExpenseViewController?
  var dataStore: IncomeAndExpenseDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: IncomeAndExpenseViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: IncomeAndExpenseDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
